# Default values for akeyless-api-gateway.
replicaCount: 2
deploymentType: Deployment

# akeylessStrictMode need to be enabled when using Redhat Openshift
akeylessStrictMode: false

# Init Container image
initContainer:
  image:
    repository: busybox
    tag: 1.30.1
    pullPolicy: IfNotPresent

# Redis cache image
cache:
  image:
    repository: docker.io/bitnami/redis
    tag: 6.2
    pullPolicy: Always

# Akeyless API Gateway image
image:
  repository: akeyless/base
  pullPolicy: Always
  tag: latest

# Akeyless API Gateway service
containerName: "api-gateway"
service:
  type: ClusterIP
  ports:
  - name: web
    port: 18888 # Akeyless UI
  - name: configure-app
    port: 8000 # Configuration manager
  - name: legacy-api
    port: 8080 # Akeyless Restful API
  - name: api
    port: 8081 # Akeyless Restful API V2
  - name: hvp
    port: 8200 # HVP vault proxy
  - name: kmip
    port: 5696 # KMIP

livenessProbe:
  initialDelaySeconds: 120
  periodSeconds: 60
  failureThreshold: 10

readinessProbe:
  initialDelaySeconds: 120 # Startup can take time
  periodSeconds: 10
  timeoutSeconds: 5

ingress:
  enabled: false

akeylessUserAuth:
  clusterName: proxmox
  initialClusterDisplayName: proxmox
  # Use k8s existing secret, must include the following key: admin-access-id
  adminAccessIdExistingSecret: akeyless-creds
  # Use k8s existing secret, must include the following key: admin-access-key
  adminAccessKeyExistingSecret: akeyless-creds
  # restrict access to admin account
  restrictAccessToAdminAccount: true

universalIdentity:
  # interval im minutes, if empty the token will be rotated in token-ttl/3  max=10 
  uidRotationInterval: "5m"
  uidCreateChildTokenPerPod: "disable" #<disable/enable>

# Specifies an initial configuration for the caching section
cachingConf:
  enabled: false
  clusterCache:
    enabled: false
  proActiveCaching:
    enabled: false
    ## The minimum fetching interval in minutes (used to avoid fetching a secret too many times in a given timeframe)
    minimumFetchingTime: 6
    ## The interval in which the proactive cache is encrypted and save to disk, in minutes
    dumpInterval: 1

  # Configure metrics exporter (backend) (such as Datadog,Prometheus, etc..)
  # Provide an existing secret with the metrics configuration or use the config section
  # For more details: https://docs.akeyless.io/docs/telemetry-metrics-k8s

HPA:
  # Set the below to false in case you do not want to add Horizontal Pod AutoScaling to the StatefulSet (not recommended)
  # Note that metrics server must be installed for this to work:
  # https://github.com/kubernetes-sigs/metrics-server
  enabled: false
  minReplicas: 1
  maxReplicas: 14
  cpuAvgUtil: 50
  memAvgUtil: 50

  annotations: {}

