apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: secrets

resources:
- namespace.yaml
# renovate: datasource=github-releases depName=bitnami-labs/sealed-secrets
- https://raw.githubusercontent.com/bitnami-labs/sealed-secrets/release/v0.26.2/helm/sealed-secrets/crds/bitnami.com_sealedsecrets.yaml
