apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: akeyless-secret-store
spec:
  provider:
    akeyless:
      akeylessGWApiURL: "https://akeyless-api-gateway.secrets.svc.cluster.local:8080/v2"
      authSecretRef:
        secretRef:
          accessID:
            name: akeyless-secret-creds
            key: admin-access-id
          accessType:
            name: akeyless-secret-creds
            key: admin-access-key
