installCRDs: false
replicaCount: 1

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::AWS_ACCOUNT_ID:role/kubeNodeRole-NODEROLEID
securityContext:
  fsGroup: 1001

dns01RecursiveNameservers: ""
dns01RecursiveNameserversOnly: true
