apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &name sealed-secrets
  namespace: argocd
spec:
  destination:
    namespace: sealed-secrets
    server: https://kubernetes.default.svc
  project: default
  sources:
  # Git Repo Deployment
  - path: kubernetes/core/sealed-secrets
    repoURL: &repo https://github.com/USERNAME/REPOSITORY.git
    targetRevision: &targetRev main
  # Helm Repo Ref
  - repoURL: *repo
    targetRevision: *targetRev
    ref: values
  # Helm Chart Deployment
  - repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: *name
    targetRevision: 2.14.1
    helm:
      valueFiles:
      - $values/kubernetes/core/sealed-secrets/values.yaml
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
