# This workflow will build the bootstrapping container and
# push the resulting image to both ECR and the GHCR Registry.

name: Build and Push Bootstrapping Container
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4.1.1
      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
      # Log in to the Amazon ECR registry
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2.0.1
      # Build and push the container
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./containers
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/bootstrapping:${tag:=latest}
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/bootstrapping:${tag:=latest}
