# This workflow will run Pulumi Preview against the AWS Infrastructure
name: Pulumi Preview
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Configures AWS credentials
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4.1.1
      # Run Pulumi Preview
      - uses: pulumi/actions@v5
        with:
          command: preview
          work-dir: ./infrastructure/pulumi
          stack-name: ${{ secrets.PULUMI_STACK_NAME }}
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets._PULUMI_CONFIG_PASSPHRASE }}
